name: NewUhcHost
version: 0.1-ALPHA
description: The best new uhc host plugin
author: Xen0Xys
main: fr.xen0xys.newuhchost.NewUhcHost
commands:
  newuhchost:
    description: Open host pannel
    aliases: [nuh, uhc, host]
    permission: newuhchost.newuhchost

permissions:
  newuhchost.*:
    description: Gives access to all NewUhcHost commands
    children:
      newuhchost.newuhchost: true
      newuhchost.createhost: true
  newuhchost.newuhchost:
    description: Open host pannel
    default: true
  newuhchost.createhost:
    description: Player can create host
    default: op